---
################################################################################ 
#
# FlexPod vSphere iSCSI setup
#
################################################################################ 

################################################################################ 
# 
# vCenter Setup Section
#
################################################################################ 
- name: Setup Datacenter and Cluster
  hosts: localhost
  vars_files:
    - "./vars/iscsi-main.yml"

  tasks:
# Create Datacenter object in vCenter
#
  - include_tasks: tasks/dc_create.yml
# Cluster creation for the provisioned hosts
#
  - include_tasks: tasks/cluster_file.yml
# Cluster configuration of HA/DRS
# [specificaiton of VM Swap for cluster not available at this time]
#
  - include_tasks: tasks/cluster_configure_file.yml
# Create DVS within vCenter
#
  - include_tasks: tasks/vds_create.yml
# Create DVS Portgroups
#
  - include_tasks: tasks/vds_portgroup_create.yml
    loop: "{{ list_of_portgroups | subelements('dvs_vlan') }}"

################################################################################ 
# 
# Host Setup Section
#
################################################################################ 
- name: Setup Hosts
  hosts: esxi_iscsi
  gather_facts: no
  vars_files:
    - "./vars/iscsi-main.yml"

  tasks:
# Add provisioned hosts
# ESXi should be installed, IP/VLAN/Password configured
#
  - include_tasks: tasks/add_hosts.yml
# Configure NTP and SSH
# adjust if SSH is not needed, though currently a requirement in iSCSI deployments
#
  - include_tasks: tasks/services_tasks.yml
# Adjust base vSwitch and create additional vSwitches
#
  - include_tasks: tasks/vswitch_tasks.yml
# Adjust initial iSCSI vSwitch and create a B iSCSI vSwitch
#
  - include_tasks: tasks/iscsi_vswitch_tasks.yml
# Create and modify portgroups for management, vMotion, and NFS
#
  - include_tasks: tasks/portgroup_tasks.yml
# Create portgroup for iSCSI-B
#
  - include_tasks: tasks/iscsi_portgroup_tasks.yml
# Create VMKernel for vMotion
#
  - include_tasks: tasks/vmotion_vmk.yml
# Create VMKernel for NFS
#
  - include_tasks: tasks/nfs_vmk.yml
# Modify VMKernel for iSCSI A
#
  - include_tasks: tasks/iscsi_a_vmk.yml
# Create VMKernel for iSCSI B
#
  - include_tasks: tasks/iscsi_b_vmk.yml
# Add NFS Datastores to hosts
#
  - include_tasks: tasks/nfs_add.yml
    loop: "{{ list_of_nfs }}"
# Add iSCSI dynamic send targets to hosts
#
  - include_tasks: tasks/iscsi_send_targets.yml
    loop: "{{ iscsi_targets }}"

################################################################################ 
# 
# Host Add to DVS as a serial operation to prevent a problem with parallel add
#
################################################################################ 
- name: Add Hosts to DVS
  hosts: esxi_iscsi
  gather_facts: no
  serial: 1
  vars_files:
    - "./vars/iscsi-main.yml"

  tasks:
# Add hosts to DVS
#
  - include_tasks: tasks/dvs_host_tasks.yml

