---
################################################################################ 
#
# Cisco Converged Infrastructure Ansible Playbook
#
################################################################################ 

################################################################################ 
# 
# vCenter Setup Section
#
################################################################################ 
- hosts: localhost
  vars_files:
    - "./vars/vsphere-main.yml"
  roles:
    - vCenter

################################################################################ 
# 
# Host Setup Section
#
################################################################################ 
- hosts: esxi_iscsi
#- hosts: esxi_fc
  gather_facts: no
  vars_files:
    - "./vars/vsphere-main.yml"
  roles:
    - Hosts

- hosts: esxi_iscsi
#- hosts: esxi_fc
  gather_facts: no
  serial: 1
  vars_files:
    - "./vars/vsphere-main.yml"
  roles:
    - AddToDVS

