---
- name: Host Addition
  hosts: localhost
#  hosts: esxi
  vars_files:
    - "./vars/main.yml"
    
  tasks:
  - name: Add ESXi Host to vCenter
    vmware_host:
      #    hostname: '{{ inventory_hostname }}'
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ vcenter_dc }}'
      cluster: '{{ vcenter_cluster }}'
      esxi_hostname: '{{ esxi_hostname }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      fetch_ssl_thumbprint: yes
      validate_certs: no
      state: present
    delegate_to: localhost
    #include_vars: "./vars/main.yml"
