---
  - name: vCenter vDS creation
    vmware_dvswitch:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: '{{ vcenter_dc }}'
      switch_name: '{{ app_dvs }}'
      version: '{{ dv_version }}'
      mtu: '{{ dv_mtu }}'
      uplink_quantity: '{{ dv_uplink }}'
      discovery_protocol: '{{ dv_protocol }}'
      discovery_operation: '{{ dv_operation }}'
      state: present
    delegate_to: localhost
