---
  - name: DRS setup
    vmware_cluster_drs:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: '{{ vcenter_dc }}'
      cluster_name: '{{ vcenter_cluster }}'
      enable_drs: yes
    delegate_to: localhost

  - name: HA setup
    vmware_cluster_ha:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: '{{ vcenter_dc }}'
      cluster_name: '{{ vcenter_cluster }}'
      enable_ha: yes
    delegate_to: localhost

