---
# 
# SSH connection may fail for esxcli if previous ssh known_host key has been acquired
#
  - name: Add iSCSI Send Targets to each host
    command: esxcli iscsi adapter discovery sendtarget add --address='{{ item }}':3260 --adapter=vmhba64
    args:
      warn: false
    when: configure_iscsi is defined
