---
  - name: Create iSCSI B adapter
    vmware_vmkernel:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      vswitch: '{{ iscsi_b_vswitch }}'
      portgroup: '{{ iscsi_b_portgroup }}'
      mtu: '{{ iscsi_mtu }}'
      network:
        type: 'static'
        ip_address: '{{ iscsi_b_ip }}'
        subnet_mask: '{{ iscsi_mask }}'
      state: present
    delegate_to: localhost
    when: configure_iscsi is defined

  - name: Adjust iSCSI A adapter
    vmware_vmkernel:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      vswitch: '{{ iscsi_a_vswitch }}'
      portgroup: '{{ iscsi_a_portgroup }}'
      mtu: '{{ iscsi_mtu }}'
      network:
        type: 'static'
        ip_address: '{{ iscsi_a_ip }}'
        subnet_mask: '{{ iscsi_mask }}'
      state: present
    delegate_to: localhost
    when: configure_iscsi is defined
