---
  - name: Configure NTP server
    vmware_host_ntp:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      #esxi_hostname: '{{ item.0.host }}'
      ntp_servers:
          - 172.26.163.254
    delegate_to: localhost
  
  - name: Start ntpd for added hosts
    vmware_host_service_manager:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: ntpd
      service_policy: on
    delegate_to: localhost
  
  - name: Start ssh for added hosts
    vmware_host_service_manager:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: TSM-SSH
      service_policy: on
    delegate_to: localhost

  - name: Start ESXi Shell for added hosts
    vmware_host_service_manager:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: TSM
      service_policy: on
    delegate_to: localhost
