---
################################################################################ 
# 
# Add Hosts to vCenter and configured vDS
#
################################################################################ 
# Broken off from main Hosts role to allow sequential execution as parallel 
# execution will sometimes fail within vCenter
#

# Add provisioned hosts
# ESXi should be installed, IP/VLAN/Password configured
#
   - include_tasks: add_hosts.yml

# Add hosts to DVS
#
   - include_tasks: dvs_host_tasks.yml

